feat: Update actions ✨

diff --git a/.github/workflows/check-pr-title.yml b/.github/workflows/check-pr-title.yml
--- a/.github/workflows/check-pr-title.yml
+++ b/.github/workflows/check-pr-title.yml
@@ -7,7 +7,8 @@ on:
       - edited
       - synchronize
   merge_group:
-
+  pull_request:
+    types: [synchronize, opened, reopened, labeled, unlabeled]
 
 permissions:
   pull-requests: write
@@ -73,3 +74,14 @@ jobs:
             repo: context.repo.repo,
             labels: ['breaking change']
           })
+
+  do-not-merge:
+    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
+    name: Prevent Merging
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for label
+        run: |
+          echo "Pull request is labeled as 'do not merge'"
+          echo "This workflow fails so that the pull request cannot be merged"
+          exit 1
